services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
  

  web:
    image: go-library
    ports:
      - "8080:8080"
    depends_on:
      - db